### ISSUE TITLE
[centos]使用php-x开发扩展的demo

### ISSUE THREAD

**Issue by zrlhk** [swoole/phpx#44]
我使用的环境是centos7/php7.1；
由于个人环境差异，命令应该不完全一致，本文目的是提供端到端的流程，加以命令的说明，供大家参考：

安装基本组件：
`yum install -y cmake git gcc gcc-c++ wget`

有个环境碰到gcc版本过低的问题，所以升级了gcc (可选):
```
yum install centos-release-scl-rh centos-release-scl
yum check-update
yum install devtoolset-4-gcc  devtoolset-4-gcc-c++
source /opt/rh/devtoolset-4/enable
```

下载php-x代码：
`git clone https://github.com/swoole/PHP-X.git`

进入目录
`cd PHP-X`

cmake带上php-config路径（使用php-config可以查看自己的路径）
`cmake -DPHP_CONFIG_DIR=/usr/bin`

make&&make install
```
make -j 4
sudo make install
```

添加动态链接库（和很多人一样，卡这里比较久）
```
echo /usr/local/lib>>/etc/ld.so.conf
ldconfig
```

以上php-x算安装完毕了。
下面编译个demo扩展：

```
cd examples/cpp_ext
make 
make install
```

配置扩展到php ini中：
`echo extension=cpp_ext.so>/etc/php.d/99-cppext.ini`

重启php-fpm:
`systemctl restart php-fpm.service`

完毕。此时phpinfo中已经可以看到  cpp_ext 这个扩展。

**Comment by owenliang** [comment]
谢谢分享。
