### ISSUE TITLE
Array迭代器begin删除0后，依然从0开始

### ISSUE THREAD

**Issue by zyxyueye** [swoole/phpx#51]
![image](https://user-images.githubusercontent.com/45614367/49486640-4446f680-f87a-11e8-99a3-54e0b75ca3ba.png)
函数执行两次，分别传入参数3和2

第一次执行删除 0,1,2 索引
第二执行，begin依然为0，执行删除的是0,3

![image](https://user-images.githubusercontent.com/45614367/49486708-853f0b00-f87a-11e8-81c1-af86af9c9e37.png)

**Comment by owenliang** [comment]
你好，麻烦贴一下示例代码！ @zyxyueye

**Comment by owenliang** [comment]
这是迭代器实现的bug，生成迭代器后没有跳过zend_array的空槽位，明早修复。

**Comment by owenliang** [comment]
@zyxyueye  master分支修复了一下，你试试看。
