### ISSUE TITLE
能否支持编译libphpx.so的静态库？

### ISSUE THREAD

**Issue by leoleoasd** [swoole/phpx#62]
如题
现在这样子的话 发布插件的时候必须带一个libphpx.so 十分不方便

**Comment by owenliang** [comment]
好的，敬请期待。

Leo <notifications@github.com> 于 2019年5月3日周五 下午2:15写道：

**Comment by owenliang** [comment]
@leoleoasd  master最新提交已经支持输出静态库。

更新代码，执行：

```
cmake .
make
make install
```

那么动态库和静态库都会被安装到/usr/local/lib，此后你编译扩展的gcc指令需要采用静态链接方式。
