### ISSUE TITLE
License is not consistent

### ISSUE THREAD

**Issue by ClosetMonkey** [swoole/phpx#63]
Why licensed as GPL? Apache license is easier to work with.

**Comment by ClosetMonkey** [comment]
It was made available under Apache license within the v1.9.7 branch of swoole-src (PHP_API.hpp and PHP_embed.hpp @ https://github.com/swoole/swoole-src/tree/v1.9.7)

**Comment by minbaby** [comment]
https://github.com/swoole/phpx/blob/master/LICENSE

**Comment by ClosetMonkey** [comment]
Yes, but the greater part of the project was Apache'ed by the link above. I can copy/paste 90% of phpx from swoole v1.9.7 and it will be licensed under Apache license...

**Comment by ClosetMonkey** [comment]
which I would rather not do because the Swoole team created it. I just don't understand the license difference when so much of PHPX is no longer gpl'ed

**Comment by deminy** [comment]
Thanks for reporting it. I have checked with other team members and we should use Apache 2 for most Swoole projects. The Swoole team has been busy with code development and other work; we will have those license information appropriately updated when we get a chance.

**Comment by deminy** [comment]
The project now is licensed under Apache 2. Thanks.
