### ISSUE TITLE
Mac cmake fail

### ISSUE THREAD

**Issue by zch513430014** [swoole/phpx#66]
mac version : 10.14.6 
php version: 
PHP 7.1.23 (cli) (built: Feb 22 2019 22:19:32) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

grantMac:phpx zch$ cmake .
CMake Error at CMakeLists.txt:28 (execute_process):
  execute_process called with no value for OUTPUT_VARIABLE.

PHP_INCLUDE_DIR: /usr/include/php
 -undefined dynamic_lookup
-- Configuring incomplete, errors occurred!

**Comment by GeniusLe** [comment]
删除CMakeLists.txt中28行开始的整个方法即可确保该行为php-config --ldflags
