### ISSUE TITLE
PHPX +swoole_zookeeper 无法使用

### ISSUE THREAD

**Issue by bobyang007** [swoole/phpx#74]
大神您好
编译安装新版phpx后，再重新编译 swoole_zookeeper
在查看 PHP 信息时报错，无法使用

php -v
php: malloc.c:2401: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

去掉 swoole_zookeeper 扩展后才能正常

**Comment by bobyang007** [comment]
清理掉原来的编译信息，发现早已无法编译
![image](https://user-images.githubusercontent.com/54702711/107211828-09840e80-6a41-11eb-8567-4c4488aab2cd.png)

**Comment by matyhtf** [comment]
请更新一下 repo，现在已经支持了
